version: '3'

services:

  receiver:
    build: receiver
    ports:
    - 5000:5000
    depends_on:
    - kafka

  launcher:
    build: launcher
    depends_on:
    - kafka

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_HOST_NAME=kafka
     - KAFKA_CREATE_TOPICS="receiver:1:1,launcher:1:1"
    ports:
    - 9092:9092
    - 6667:6667
    depends_on:
    - zookeeper

#  elasticsearch:
#    image: elasticsearch:6.7.0
#    ports:
#    - 9200:9200
#    - 9300:9300
#
#  kibana:
#    image: kibana:6.7.0
#    ports:
#    - 5601:5601

networks:
  default:
    driver: bridge

